# .github/workflows/update-readme.yml
on:
  schedule:
    - cron: '0 0 * * *' # run daily at 00:00 UTC [1]
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Update README
        uses: peter-evans/create-or-update-file@v3
        with:
          path: README.md
          commit-message: "chore: update last-updated date"
          content: |
            $(sed "s/<!--UPDATEDATE-->/${{ steps.date.outputs.date }}/" README.md)
          sha: ${{ steps.date.outputs.date }} # ensures idempotency [2]
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
